---
- name: Create new instances
  hosts: localhost
  roles:
    - { role: briochebcit.instance, tags: instance }

- name: Manage new instances
  hosts: webservers
  connection: ssh
  become: true
  roles:
    - { role: geerlingguy.apache, tags: apache }
    - { role: briochebcit.php, tags: php }
    - { role: briochebcit.webserver, tags: webserver }

- name: Update HAProxy servers
  hosts: lbservers
  connection: ssh
  become: true
  roles:
    - { role: briochebcit.loadbalancerconfig, tags: loadbalancer}

- name: Update Munin servers
  hosts: muninservers
  connection: ssh
  become: true
  roles:
    - { role: briochebcit.monitoring, tags: monitoring }

